### ISSUE TITLE
Overkill exceptions

### ISSUE THREAD

**Issue by aquohn** [nusCS2113-AY1920S1/forum#15]
Should we handle exceptions for cases which program flow would exclude? e.g. I want to cut the command from the input string so I use inputStr.substring(command.length()), but it's in a conditional branch that will only be reached if inputStr starts with command. Do I need to catch the IndexOutOfBoundsException?

**Comment by okkhoy** [comment]
You should decide if it is meaningful to use exceptions in this case.

**Comment by omupenguin** [comment]
Quick question, does this count as exception handling, or regular error handling? Since you can check if inputStr.length() == command.length() before executing inputStr.substring(command.length()). I am very confused about the difference between the two.

**Comment by okkhoy** [comment]
The first step is to check if they are of the same length. If they are not, what do you do, throw an exception.
@aquohn my apologies, I think I misread your question the first time. If the conditional branch is reached due to a command string, but some mess happens later, you use exceptions to handle the situation.
