### ISSUE TITLE
text-ui-test: Issues for runtest.sh involving Task classes

### ISSUE THREAD

**Issue by lmtaek** [nusCS2113-AY1920S1/forum#30]
I've been having a bit of an issue with getting my runtest.sh file to run successfully, and I believe it involves locating my Task class and its subclasses. Every time I attempt to run the file, an error is displayed stating: "error: cannot find symbol" with the compiler pointing to any reference of the Task class or its subclasses within my main method. 

I've tried fixing the issue by identifying the classes' paths in the runtest.sh file, but either I'm identifying the path wrong, or the issue calls for a different solution. 

Any suggestions? Anything helps! 
Thanks.

**Comment by kevin996231** [comment]
It probably results from not compiling all the classes.
try changing
`if ! javac -cp ../src -Xlint:none -d ../bin ../src/main/java/Duke.java`
into
`if ! javac -cp ../src -Xlint:none -d ../bin ../src/main/java/*`

**Comment by lmtaek** [comment]
I'm in agreement about it likely being due to all the classes not compiling--I tried your advice, but now I'm getting "error: invalid flag: ../src/main/java/Duke.class" errors. I tried encasing the `../src/main/java/*` portion in quotes to see if it would help, but then the invalid flag error points to `../src/main/java/*` instead.

Any ideas? It looks like most recommended solutions involve checking the spacing of the provided path, but I don't think that's the issue here.

**Comment by gowgos5** [comment]
try changing to this instead. I suspect the classpath is not properly specified.

```
if ! javac -cp ../src/main/java -Xlint:none -d ../bin ../src/main/java/Duke.java
```

**Comment by lmtaek** [comment]
That seemed to do the trick, for the most part. Thank you! The runtest.sh file ran, and seems to have compiled my Task classes. 

The one issue is that it can't seem to reference my data.txt file. The data file's directory in the same location, generally:`../src/main/java`; the actual path is `../src/main/java/data/data.txt`. 

Sorry to ask so many questions, but should I try identifying a path for the file prior to the code's compilation? Or are there better methods of handling this?

**Comment by aquohn** [comment]
Since you hard-coded the path, when you run the class from a script in the `text-ui-test` folder, the path is relative to that folder. If you're using IntelliJ, the program should be run from the project root, so your hardcoded path would be `[project root]/src/main/java/data/data.txt`. What you want when you launch it from `[project root]/text-ui-test` is `../src/main/java/data/data.txt`.

Instead of changing the hardcoded path, I think a cleaner fix would be to run `cd ..` before `java` in the shell script. The downside is that your input and output files would need to be prefixed with `text-ui-test\`.

**Comment by chelsea148629** [comment]
For answering why the error occurs and for someone who use the  `*` :
The asterisk `*` here means the part of it can be replace by any string.

So instead of `../src/main/java/* `, using `../src/main/java/*.java ` is better.

If you have `Duke.java` `Task.java` and `Duke.class` `Task.class`(which could be generated during the previous compilation) under your ` ../src/main/java/` directory, using `*` will made the script try to compile all of them which we don't want to, while using `*.java` will only compile `Duke.java` and `Task.java`

**Comment by aquohn** [comment]
The `-d` switch should make sure the classes go elsewhere though.

**Comment by lmtaek** [comment]
I think I've figured out the issue for the most part, in terms of referencing my hardcoded data.txt file. 

Because I hardcoded my data.txt file's path (and it's a relative path), the issue with the compiled Duke class when running the shellscript was that it was placed in the bin directory (`[project root]/bin`), so when it attempted to follow the relative path, it couldn't find the file's location. 

With that in mind, I managed to get things in order! 

Thanks for all the help!
