### ISSUE TITLE
Suddenly Unable to Load Main Class Duke

### ISSUE THREAD

**Issue by Sfloydzy** [nusCS2113-AY1920S1/forum#9]
I was running IntelliJ just fine previously. I coded ran and committed up to level 2 before updating my system environmental paths to include the JKD 11 bin and importing gradle. After doing so I got the following error. After removing the path and gradle, I am still not able to resolve this issue. Nothing else about my code has changed but I can no longer run code which worked previously before.

Terminal Message:
![errorintellij](https://user-images.githubusercontent.com/42894517/63587658-24f22400-c5d7-11e9-8dbb-344836b8fa90.PNG)

Duke Configuration:
![image](https://user-images.githubusercontent.com/42894517/63587763-579c1c80-c5d7-11e9-9c01-d23b73689120.png)

**Comment by j-lum** [comment]
Check `build.gradle` and read the comments in there.

**Comment by limsiying** [comment]
Hi! I had the same error and it was because my classpath for my main class was wrong (unless I understood it wrongly ah HAHAHA).  You might want to try "java Duke" in the folder which contains Duke.class; can try looking in duke\build\classes :') Hope this helps!
![image](https://user-images.githubusercontent.com/42372947/63610393-f93d6100-c60b-11e9-851a-ae485b57153b.png)

**Comment by Jefferson111** [comment]
I think we should have a lecture on Gradle and Intellij.

**Comment by okkhoy** [comment]
There will be one when it is time 😈

**Comment by Sfloydzy** [comment]
Hi thanks for all the comments. Managed to solve the issue by changing the class path to duke.main.
